[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
no-match-contract = 'StakeManagerTestable'
optimizer = true
optimizer_runs = 200
via_ir = true
cache_path = 'forge-cache'
verbosity = 2
memory_limit = 40003554432
gas_limit = "18446744073709551615"
libraries = ["contracts/common/lib/Common.sol:Common:0x5FbDB2315678afecb367f032d93F642f64180aa3", "contracts/root/predicates/TransferWithSigUtils.sol:TransferWithSigUtils:0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"] 

ffi = true
remappings = [
  "openzeppelin-solidity/=node_modules/openzeppelin-solidity/",
  "@ensdomains/=node_modules/@ensdomains/",
  "eth-gas-reporter/=node_modules/eth-gas-reporter/",
  "forge-std/=lib/forge-std/src/",
  "hardhat/=node_modules/hardhat/"
]
fs_permissions = [{ access = "read", path = "./scripts/"}, { access = "read", path = "./test/"},  { access = "read", path = "./out/"}, { access = "read-write", path = "./contractAddresses.json" }]
auto_detect_solc = true

[invariant]
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[profile.intense.fuzz]
runs = 10000
max_test_rejects = 999999

[fmt]
line_length = 160
number_underscore = "thousands"

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
mainnet = "https://mainnet.infura.io/v3/${INFURA_TOKEN}"
goerli = "https://goerli.infura.io/v3/${INFURA_TOKEN}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_TOKEN}"
polygon_pos = "https://polygon-mainnet.infura.io/v3/${INFURA_TOKEN}"
mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_TOKEN}"
polygon_zkevm = "https://zkevm-rpc.com"
polygon_zkevm_testnet = "https://rpc.public.zkevm-test.net"

# [etherscan]
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
# goerli = { key = "${ETHERSCAN_API_KEY}" }
# sepolia = { key = "${ETHERSCAN_API_KEY}" }
# polygon_pos = { key = "${POLYGONSCAN_API_KEY}" }
# mumbai = { key = "${POLYGONSCAN_API_KEY}" }
# polygon_zkevm = { key = "${POLYGONSCAN_ZKEVM_API_KEY}" }
# polygon_zkevm_testnet = { key = "${POLYGONSCAN_ZKEVM_API_KEY}" }

[fuzz]
allowed-write-paths = ["scripts/"]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
