#!/usr/bin/env bash

set -e

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

source "$SCRIPT_DIR/lib.sh"

echo -e "${GREEN}Starting local Reth client (devnet)...${NC}"

check_reth_firehose_tracer
check_jq

# The container name ending with '-el-1' is generated by the `run_playground_devnet.sh` script
if ! docker ps --format '{{.Names}}' | grep -q '-el-1$'; then
    echo -e "${RED}Error: Playground doesn't seem to be running. Please start it first with:${NC}"
    echo "  ./scripts/ethereum_devnet/run_playground_devnet.sh"
    exit 1
fi

# Use playground genesis and configuration
playground_path="$ROOT/.playground/chain"
jwt_secret_file="$playground_path/jwtsecret"
data_dir="/tmp/reth-playground-data"
l1_beacon_rpc_url="http://localhost:3500"

# Clean up any existing data
if [[ -d "$data_dir" ]]; then
    echo "Removing existing Reth data directory: $data_dir"
    rm -rf "$data_dir"
fi

# Wait for primary Reth to be ready
echo "Waiting for primary Reth to be ready..."
max_attempts=30
attempt=1
while [ $attempt -le $max_attempts ]; do
    if curl -s http://localhost:8545 -X POST -H "Content-Type: application/json" \
        --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' > /dev/null 2>&1; then
        break
    fi
    echo "Attempt $attempt/$max_attempts: primary Reth not ready yet..."
    sleep 2
    attempt=$((attempt + 1))
done

if [ $attempt -gt $max_attempts ]; then
    echo -e "${RED}Error: Primary Reth didn't become ready within expected time${NC}"
    exit 1
fi

echo -e "${GREEN}Primary Reth is ready!${NC}"

# Wait for Beacon to be ready
echo "Waiting for Beacon to be ready..."
max_attempts=30
attempt=1
while [ $attempt -le $max_attempts ]; do
    if curl -s --max-time 2 "$l1_beacon_rpc_url/eth/v1/node/version" > /dev/null 2>&1; then
        break
    fi
    echo "Attempt $attempt/$max_attempts: Beacon not ready yet..."
    sleep 2
    attempt=$((attempt + 1))
done

if [ $attempt -gt $max_attempts ]; then
    echo -e "${RED}Error: Beacon didn't become ready within expected time${NC}"
    exit 1
fi

echo -e "${GREEN}Beacon is ready!${NC}"

# Initialize Reth with playground genesis
"$reth" init --datadir="$data_dir" --chain="$playground_path/genesis.json" 2>/dev/null

# Get primary Reth enode for peer connection.
# The primary Reth runs in Docker; we resolve its published P2P host port so that the
# enode can be dialled from the host. If the port mapping is unavailable the connection
# attempt is skipped (the node will still sync via the Engine API driven by the beacon).
echo "Getting primary Reth enode for peer connection..."
PRIMARY_RETH_CONTAINER=$(docker ps --format '{{.Names}}' | grep '-el-1$' | head -1)
PRIMARY_P2P_HOST_PORT=$(docker port "$PRIMARY_RETH_CONTAINER" 30303/tcp 2>/dev/null | cut -d: -f2 || true)

RETH_ENODE=$(curl -s http://localhost:8545 -X POST -H "Content-Type: application/json" \
    --data '{"jsonrpc":"2.0","method":"admin_nodeInfo","params":[],"id":1}' | \
    jq -r '.result.enode' 2>/dev/null || true)

if [ -n "$RETH_ENODE" ] && [ "$RETH_ENODE" != "null" ] && [ -n "$PRIMARY_P2P_HOST_PORT" ]; then
    # Replace IP and port in the enode with the host-accessible values
    RETH_ENODE=$(echo "$RETH_ENODE" | sed "s/@[^:]*:[0-9]*\$/@127.0.0.1:$PRIMARY_P2P_HOST_PORT/")
    echo "Primary Reth enode: $RETH_ENODE"
else
    echo -e "${YELLOW}Warning: Could not resolve primary Reth enode/P2P port — P2P sync disabled, relying on Engine API only${NC}"
    RETH_ENODE=""
fi

# Build reth command
reth_extra_args=(
    "node"
    "--datadir=$data_dir"
    "--chain=$playground_path/genesis.json"
    "--http"
    "--http.addr=0.0.0.0"
    "--http.port=8547"
    "--http.api=eth,net,web3,debug,admin"
    "--authrpc.addr=0.0.0.0"
    "--authrpc.jwtsecret=$jwt_secret_file"
    "--authrpc.port=8552"
    "--port=30304"
    "--engine.persistence-threshold=0"
    "--engine.memory-block-buffer-target=0"
    "--color=never"
    "--disable-discovery"
    "-vvvv"
)

if [ -n "$RETH_ENODE" ]; then
    reth_extra_args+=("--peers=$RETH_ENODE")
fi

# Function to add primary Reth as a peer via admin_addPeer once our node is up
add_peer() {
    if [ -z "$RETH_ENODE" ]; then
        return
    fi

    echo "Waiting for secondary Reth to be ready for peer addition..."
    local max_attempts=30
    local attempt=1

    while [ $attempt -le $max_attempts ]; do
        if curl -s --max-time 2 http://localhost:8547 -X POST -H "Content-Type: application/json" \
            --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' > /dev/null 2>&1; then
            break
        fi
        echo "Attempt $attempt/$max_attempts: Waiting for secondary Reth RPC..."
        sleep 2
        attempt=$((attempt + 1))
    done

    if [ $attempt -gt $max_attempts ]; then
        echo -e "${YELLOW}Secondary Reth RPC not ready, skipping manual peer addition${NC}"
        return
    fi

    echo "Adding primary Reth as peer: $RETH_ENODE"
    curl -s -X POST -H "Content-Type: application/json" \
        --data "{\"jsonrpc\":\"2.0\",\"method\":\"admin_addPeer\",\"params\":[\"$RETH_ENODE\"],\"id\":1}" \
        http://localhost:8547 > /dev/null 2>&1 && echo "Peer added successfully" || \
        echo -e "${YELLOW}Manual peer addition failed${NC}"
}

echo -e "${YELLOW}Starting local Reth (devnet) with command:${NC}"
echo "$reth ${reth_extra_args[*]}"
echo ""

"$reth" "${reth_extra_args[@]}" &
RETH_PID=$!

trap 'kill -TERM $RETH_PID 2>/dev/null; exit 0' SIGTERM SIGINT

add_peer

wait $RETH_PID
