#!/usr/bin/env bash

set -e

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

source "$SCRIPT_DIR/lib.sh"

echo -e "${GREEN}Starting local Besu secondary client...${NC}"

check_besu


# The '^chain-el-1$' is generated by the `run_playground_devnet.sh` script
if ! docker ps --format '{{.Names}}' | grep -q '^chain-el-1$'; then
    echo -e "${RED}Error: Playground doesn't seem to be running. Please start it first with:${NC}"
    echo "  ./scripts/ethereum_devnet/run_playground_devnet.sh"
    exit 1
fi

# Use playground genesis and configuration
playground_path="$ROOT/.playground/chain"
jwt_secret_file="$playground_path/jwtsecret"
data_dir="/tmp/geth-playground-data"
l1_beacon_rpc_url="http://localhost:3500"

# Clean up any existing data
if [[ -d "$data_dir" ]]; then
    echo "Removing existing Besu data directory: $data_dir"
    rm -rf "$data_dir"
fi

# Wait for Reth to be ready
echo "Waiting for Reth to be ready..."
max_attempts=30
attempt=1
while [ $attempt -le $max_attempts ]; do
    if curl -s http://localhost:8545 -X POST -H "Content-Type: application/json" \
        --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' > /dev/null 2>&1; then
        break
    fi
    echo "Attempt $attempt/$max_attempts: Reth not ready yet..."
    sleep 2
    attempt=$((attempt + 1))
done

if [ $attempt -gt $max_attempts ]; then
    echo -e "${RED}Error: Reth didn't become ready within expected time${NC}"
    exit 1
fi

echo -e "${GREEN}Reth is ready!${NC}"

# Wait for Beacon to be ready
echo "Waiting for Beacon to be ready..."
max_attempts=30
attempt=1
while [ $attempt -le $max_attempts ]; do
    if curl -s --max-time 2 "$l1_beacon_rpc_url/eth/v1/node/version" > /dev/null 2>&1; then
        break
    fi
    echo "Attempt $attempt/$max_attempts: Beacon not ready yet..."
    sleep 2
    attempt=$((attempt + 1))
done

if [ $attempt -gt $max_attempts ]; then
    echo -e "${RED}Error: Beacon didn't become ready within expected time${NC}"
    exit 1
fi

echo -e "${GREEN}Beacon is ready!${NC}"

# Ensure genesis.json has ethash config for Besu compatibility
if ! jq -e '.config.ethash' "$playground_path/genesis.json" > /dev/null 2>&1; then
    echo "Adding ethash config to genesis.json for Besu compatibility..."
    jq '.config.ethash = {}' "$playground_path/genesis.json" > "$playground_path/genesis.json.tmp" && mv "$playground_path/genesis.json.tmp" "$playground_path/genesis.json"
    echo "Ethash config added successfully"
else
    echo "Genesis.json already has ethash config"
fi

# Get genesis block root for checkpoint
echo "Getting genesis block root for checkpoint..."
genesis_root=$(curl -sS "$l1_beacon_rpc_url/eth/v1/beacon/headers/0" 2>/dev/null | jq -r '.data.root' 2>/dev/null || echo "")

# Get Reth enode for bootnodes
echo "Getting Reth enode for peer connection..."
RETH_ENODE=$(curl -s http://localhost:8545 -X POST -H "Content-Type: application/json" \
    --data '{"jsonrpc":"2.0","method":"admin_nodeInfo","params":[],"id":1}' | \
    jq -r '.result.enode' 2>/dev/null)

if [ -z "$RETH_ENODE" ] || [ "$RETH_ENODE" = "null" ]; then
    echo -e "${RED}Error: Could not get Reth enode${NC}"
    exit 1
fi
RETH_ENODE=$(printf "$RETH_ENODE" | sed 's/@[^@]*:/@127.0.0.1:/')

echo "Reth enode: $RETH_ENODE"

# Build besu command - similar to the firehose besu script but as secondary client
besu_extra_args=(
    "--host-allowlist=*"
    "--data-path=$data_dir"
    "--genesis-file=$playground_path/genesis.json"
    "--network-id=1337"
    "--rpc-http-cors-origins=all"
    "--rpc-http-api=ETH,NET,WEB3,ENGINE,DEBUG,ADMIN"
    "--rpc-http-enabled"
    "--rpc-http-port=8547"  # Secondary EL port (matching geth's port)
    "--rpc-http-host=0.0.0.0"
    "--engine-rpc-enabled"
    "--engine-host-allowlist=*"
    "--engine-rpc-port=8552"  # Engine API port (matching geth's authrpc port)
    "--engine-jwt-secret=$jwt_secret_file"
    "--logging=INFO"
    "--discovery-enabled=false"
    "--p2p-port=30304"  # Use different P2P port than geth
)

# Function to add Reth peer manually
add_peer() {
    echo "Waiting for Besu to be ready for peer addition..."
    local max_attempts=30
    local attempt=1

    while [ $attempt -le $max_attempts ]; do
        # Check if Besu RPC is responding
        if curl -s --max-time 2 http://localhost:8547 -X POST -H "Content-Type: application/json" \
            --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' > /dev/null 2>&1; then
            break
        fi
        echo "Attempt $attempt/$max_attempts: Waiting for Besu RPC..."
        sleep 2
        attempt=$((attempt + 1))
    done

    if [ $attempt -gt $max_attempts ]; then
        echo -e "${RED}Besu RPC not ready, skipping manual peer addition${NC}"
        return
    fi

    echo "Adding Reth peer manually: $RETH_ENODE"

    # Use RPC to add peer
    curl -s -X POST -H "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\",\"method\":\"admin_addPeer\",\"params\":[\"$RETH_ENODE\"],\"id\":1}" \
        http://localhost:8547 > /dev/null 2>&1 && echo "Peer added successfully" || echo -e "${YELLOW}Manual peer addition failed${NC}"
}


echo -e "${YELLOW}Starting local Besu with command:${NC}"
echo "$besu ${besu_extra_args[*]}"
echo ""

# Start besu
"$besu" "${besu_extra_args[@]}" &
BESU_PID=$!

trap 'kill -TERM $BESU_PID 2>/dev/null' SIGTERM SIGINT

# Try to add peer manually
add_peer

# Wait for besu process
wait $BESU_PID
