networks:
  devnet-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    networks:
      - devnet-network
    ports:
      - "9545:9545"
    entrypoint: ["anvil"]
    volumes:
      - ./data/anvil-db:/data/anvil-db
    command:
      [
        "--block-time=1",
        "--state=/data/anvil-db",
        "--accounts=10",
        "--gas-limit=1000000000000",
        "--gas-price=1",
        "--code-size-limit=10000000000",
        "--port=9545",
        "--host=0.0.0.0",
        "--verbosity",
        "--mnemonic",
        "clock radar mass judge dismiss just intact mind resemble fringe diary casino",
      ]

  rabbit0:
    image: "rabbitmq:3-management"
    container_name: rabbit0
    networks:
      - devnet-network

  heimdall0:
    build:
      context: https://github.com/maticnetwork/heimdall.git#develop
      dockerfile: Dockerfile
    entrypoint: ["bash"]
    command:
      [
        "-c",
        "sleep 5; heimdalld start --home=/var/lib/heimdall --chain=/var/lib/heimdall/config/genesis.json --bridge --all --rest-server",
      ]
    container_name: heimdall0
    restart: on-failure
    depends_on:
      - rabbit0
    networks:
      - devnet-network
    volumes:
      - ./data/heimdalld:/var/lib/heimdall

    ports:
      - "1317:1317"
      - "26657:26657"

  bor0:
    build:
      context: https://github.com/maticnetwork/bor.git#${TAG}
      dockerfile: Dockerfile

    container_name: bor0
    entrypoint: ["bor"]
    command:
      [
        "server",
        "--config=/var/lib/bor/config.toml",
        "--chain=/var/lib/bor/genesis.json",
        "--identity=matic-cli",
        "--datadir=/var/lib/bor/data",
        "--port=30303",
        "--bor.heimdall=http://heimdall0:1317",
        "--http",
        "--http.addr=0.0.0.0",
        "--ws",
        "--ws.addr=0.0.0.0",
        "--ws.port=8546",
        "--ws.api=eth,txpool,net,web3,bor",
        "--http.vhosts=*",
        "--http.corsdomain=*",
        "--ws.origins=*",
        "--http.port=8545",
        "--ipcpath=/var/lib/bor/data/bor.ipc",
        "--http.api=personal,eth,net,web3,txpool,miner,admin,bor,debug",
        "--bor.logs=true",
        "--syncmode=full",
        "--miner.gaslimit=2000000000",
        "--txpool.nolocals",
        "--txpool.accountslots=128",
        "--txpool.globalslots=20000",
        "--txpool.lifetime=0h16m0s",
        "--unlock=0x4196A1a1E21a53e1BAA3A0A5a2A1203571B250cD",
        "--miner.etherbase=0x4196A1a1E21a53e1BAA3A0A5a2A1203571B250cD",
        "--disable-bor-wallet=false",
        "--keystore=/var/lib/bor/keystore",
        "--password=/var/lib/bor/password.txt",
        "--allow-insecure-unlock",
        "--mine",
      ]
    networks:
      devnet-network:
        ipv4_address: 172.20.1.100
    environment:
      - HEIMDALL_URL=http://heimdall0:1317
    volumes:
      - ./data/bor:/var/lib/bor

    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
